export const GET_CUSTOMER_VIEW = 'GET_CUSTOMER_VIEW';
export const GET_CUSTOMER_VIEW_SUCCESS = 'GET_CUSTOMER_VIEW_SUCCESS';
export const GET_CUSTOMER_VIEW_FAIL = 'GET_CUSTOMER_VIEW_FAIL';

export const GET_SHIPMENT_VIEW = 'GET_SHIPMENT_VIEW';
export const GET_SHIPMENT_VIEW_SUCCESS = 'GET_SHIPMENT_VIEW_SUCCESS';
export const GET_SHIPMENT_VIEW_FAIL = 'GET_SHIPMENT_VIEW_FAIL';

export const GET_INVOICE_VIEW = 'GET_INVOICE_VIEW';
export const GET_INVOICE_VIEW_SUCCESS = 'GET_INVOICE_VIEW_SUCCESS';
export const GET_INVOICE_VIEW_FAIL = 'GET_INVOICE_VIEW_FAIL';

export const GET_ADMIN_MEMBER_VIEW = 'GET_ADMIN_MEMBER_VIEW';
export const GET_ADMIN_MEMBER_VIEW_SUCCESS = 'GET_ADMIN_MEMBER_VIEW_SUCCESS';
export const GET_ADMIN_MEMBER_VIEW_FAIL = 'GET_ADMIN_MEMBER_VIEW_FAIL';

export const PATCH_SHIPMENTS_ADMIN = 'PATCH_SHIPMENTS_ADMIN';
export const PATCH_SHIPMENTS_ADMIN_SUCCESS = 'PATCH_SHIPMENTS_ADMIN_SUCCESS';
export const PATCH_SHIPMENTS_ADMIN_FAIL = 'PATCH_SHIPMENTS_ADMIN_FAIL';

export const PATCH_INVOICE_ADMIN = 'PATCH_INVOICE_ADMIN';
export const PATCH_INVOICE_ADMIN_SUCCESS = 'PATCH_INVOICE_ADMIN_SUCCESS';
export const PATCH_INVOICE_ADMIN_FAIL = 'PATCH_INVOICE_ADMIN_FAIL';

export const GET_ADMIN_MEMBER_DETAIL = 'GET_ADMIN_MEMBER_DETAIL';
export const GET_ADMIN_MEMBER_DETAIL_SUCCESS = 'GET_ADMIN_MEMBER_DETAIL_SUCCESS';
export const GET_ADMIN_MEMBER_DETAIL_FAIL = 'GET_ADMIN_MEMBER_DETAIL_FAIL';

export const GET_ADMIN_INVOICE_DETAIL = 'GET_ADMIN_INVOICE_DETAIL';
export const GET_ADMIN_INVOICE_DETAIL_SUCCESS = 'GET_ADMIN_INVOICE_DETAIL_SUCCESS';
export const GET_ADMIN_INVOICE_DETAIL_FAIL = 'GET_ADMIN_INVOICE_DETAIL_FAIL';

export const GET_ADMIN_SHIPMENT_DETAIL = 'GET_ADMIN_SHIPMENT_DETAIL';
export const GET_ADMIN_SHIPMENT_DETAIL_SUCCESS = 'GET_ADMIN_SHIPMENT_DETAIL_SUCCESS';
export const GET_ADMIN_SHIPMENT_DETAIL_FAIL = 'GET_ADMIN_SHIPMENT_DETAIL_FAIL';

export const PATCH_MEMBER_ADMIN = 'PATCH_MEMBER_ADMIN';
export const PATCH_MEMBER_ADMIN_SUCCESS = 'PATCH_MEMBER_ADMIN_SUCCESS';
export const PATCH_MEMBER_ADMIN_FAIL = 'PATCH_MEMBER_ADMIN_FAIL';

export const ADD_MEMBER_ADMIN = 'ADD_MEMBER_ADMIN';
export const ADD_MEMBER_ADMIN_SUCCESS = 'ADD_MEMBER_ADMIN_SUCCESS';
export const ADD_MEMBER_ADMIN_FAIL = 'ADD_MEMBER_ADMIN_FAIL';

export const DELETE_SHIPMENT_ADMIN = 'DELETE_SHIPMENT_ADMIN';
export const DELETE_SHIPMENT_ADMIN_SUCCESS = 'DELETE_SHIPMENT_ADMIN_SUCCESS';
export const DELETE_SHIPMENT_ADMIN_FAIL = 'DELETE_SHIPMENT_ADMIN_FAIL';

export const DELETE_MEMBER_ADMIN = 'DELETE_MEMBER_ADMIN';
export const DELETE_MEMBER_ADMIN_SUCCESS = 'DELETE_MEMBER_ADMIN_SUCCESS';
export const DELETE_MEMBER_ADMIN_FAIL = 'DELETE_MEMBER_ADMIN_FAIL';

export const DELETE_INVOICE_ADMIN = 'DELETE_INVOICE_ADMIN';
export const DELETE_INVOICE_ADMIN_SUCCESS = 'DELETE_INVOICE_ADMIN_SUCCESS';
export const DELETE_INVOICE_ADMIN_FAIL = 'DELETE_INVOICE_ADMIN_FAIL';

export const GET_TERMS_ADMIN = 'GET_TERMS_ADMIN';
export const GET_TERMS_ADMIN_SUCCESS = 'GET_TERMS_ADMIN_SUCCESS';
export const GET_TERMS_ADMIN_FAIL = 'GET_TERMS_ADMIN_FAIL';

export const GET_FAQ_ADMIN = 'GET_FAQ_ADMIN';
export const GET_FAQ_ADMIN_SUCCESS = 'GET_FAQ_ADMIN_SUCCESS';
export const GET_FAQ_ADMIN_FAIL = 'GET_FAQ_ADMIN_FAIL';

export const ADD_FAQ_ADMIN = 'ADD_FAQ_ADMIN';
export const ADD_FAQ_ADMIN_SUCCESS = 'ADD_FAQ_ADMIN_SUCCESS';
export const ADD_FAQ_ADMIN_FAIL = 'ADD_FAQ_ADMIN_FAIL';

export const ADD_TERMS_ADMIN = 'ADD_TERMS_ADMIN';
export const ADD_TERMS_ADMIN_SUCCESS = 'ADD_TERMS_ADMIN_SUCCESS';
export const ADD_TERMS_ADMIN_FAIL = 'ADD_TERMS_ADMIN_FAIL';

export const PATCH_TERMS_ADMIN = 'PATCH_TERMS_ADMIN';
export const PATCH_TERMS_ADMIN_SUCCESS = 'PATCH_TERMS_ADMIN_SUCCESS';
export const PATCH_TERMS_ADMIN_FAIL = 'PATCH_TERMS_ADMIN_FAIL';

export const PATCH_FAQ_ADMIN = 'PATCH_FAQ_ADMIN';
export const PATCH_FAQ_ADMIN_SUCCESS = 'PATCH_FAQ_ADMIN_SUCCESS';
export const PATCH_FAQ_ADMIN_FAIL = 'PATCH_FAQ_ADMIN_FAIL';

export const GET_ORIGIN_PHOTO = 'GET_ORIGIN_PHOTO';
export const GET_ORIGIN_PHOTO_SUCCESS = 'GET_ORIGIN_PHOTO_SUCCESS';
export const GET_ORIGIN_PHOTO_FAIL = 'GET_ORIGIN_PHOTO_FAIL';

export const GET_ORIGIN_PHOTO_WITH_PAGINATION = 'GET_ORIGIN_PHOTO_WITH_PAGINATION';
export const GET_ORIGIN_PHOTO_WITH_PAGINATION_SUCCESS = 'GET_ORIGIN_PHOTO_WITH_PAGINATION_SUCCESS';
export const GET_ORIGIN_PHOTO_WITH_PAGINATION_FAIL = 'GET_ORIGIN_PHOTO_WITH_PAGINATION_FAIL';