export const GET_CUSTOMER_VIEW = 'GET_CUSTOMER_VIEW';
export const GET_CUSTOMER_VIEW_SUCCESS = 'GET_CUSTOMER_VIEW_SUCCESS';
export const GET_CUSTOMER_VIEW_FAIL = 'GET_CUSTOMER_VIEW_FAIL';

export const GET_SHIPMENT_VIEW = 'GET_SHIPMENT_VIEW';
export const GET_SHIPMENT_VIEW_SUCCESS = 'GET_SHIPMENT_VIEW_SUCCESS';
export const GET_SHIPMENT_VIEW_FAIL = 'GET_SHIPMENT_VIEW_FAIL';

export const GET_INVOICE_VIEW = 'GET_INVOICE_VIEW';
export const GET_INVOICE_VIEW_SUCCESS = 'GET_INVOICE_VIEW_SUCCESS';
export const GET_INVOICE_VIEW_FAIL = 'GET_INVOICE_VIEW_FAIL';

export const GET_ADMIN_MEMBER_VIEW = 'GET_ADMIN_MEMBER_VIEW';
export const GET_ADMIN_MEMBER_VIEW_SUCCESS = 'GET_ADMIN_MEMBER_VIEW_SUCCESS';
export const GET_ADMIN_MEMBER_VIEW_FAIL = 'GET_ADMIN_MEMBER_VIEW_FAIL';

export const PATCH_SHIPMENTS_ADMIN = 'PATCH_SHIPMENTS_ADMIN';
export const PATCH_SHIPMENTS_ADMIN_SUCCESS = 'PATCH_SHIPMENTS_ADMIN_SUCCESS';
export const PATCH_SHIPMENTS_ADMIN_FAIL = 'PATCH_SHIPMENTS_ADMIN_FAIL';

export const PATCH_INVOICE_ADMIN = 'PATCH_INVOICE_ADMIN';
export const PATCH_INVOICE_ADMIN_SUCCESS = 'PATCH_INVOICE_ADMIN_SUCCESS';
export const PATCH_INVOICE_ADMIN_FAIL = 'PATCH_INVOICE_ADMIN_FAIL';

export const GET_ADMIN_MEMBER_DETAIL = 'GET_ADMIN_MEMBER_DETAIL';
export const GET_ADMIN_MEMBER_DETAIL_SUCCESS = 'GET_ADMIN_MEMBER_DETAIL_SUCCESS';
export const GET_ADMIN_MEMBER_DETAIL_FAIL = 'GET_ADMIN_MEMBER_DETAIL_FAIL';

export const GET_ADMIN_INVOICE_DETAIL = 'GET_ADMIN_INVOICE_DETAIL';
export const GET_ADMIN_INVOICE_DETAIL_SUCCESS = 'GET_ADMIN_INVOICE_DETAIL_SUCCESS';
export const GET_ADMIN_INVOICE_DETAIL_FAIL = 'GET_ADMIN_INVOICE_DETAIL_FAIL';

export const GET_ADMIN_SHIPMENT_DETAIL = 'GET_ADMIN_SHIPMENT_DETAIL';
export const GET_ADMIN_SHIPMENT_DETAIL_SUCCESS = 'GET_ADMIN_SHIPMENT_DETAIL_SUCCESS';
export const GET_ADMIN_SHIPMENT_DETAIL_FAIL = 'GET_ADMIN_SHIPMENT_DETAIL_FAIL';

export const PATCH_MEMBER_ADMIN = 'PATCH_MEMBER_ADMIN';
export const PATCH_MEMBER_ADMIN_SUCCESS = 'PATCH_MEMBER_ADMIN_SUCCESS';
export const PATCH_MEMBER_ADMIN_FAIL = 'PATCH_MEMBER_ADMIN_FAIL';

export const ADD_MEMBER_ADMIN = 'ADD_MEMBER_ADMIN';
export const ADD_MEMBER_ADMIN_SUCCESS = 'ADD_MEMBER_ADMIN_SUCCESS';
export const ADD_MEMBER_ADMIN_FAIL = 'ADD_MEMBER_ADMIN_FAIL';

export const DELETE_SHIPMENT_ADMIN = 'DELETE_SHIPMENT_ADMIN';
export const DELETE_SHIPMENT_ADMIN_SUCCESS = 'DELETE_SHIPMENT_ADMIN_SUCCESS';
export const DELETE_SHIPMENT_ADMIN_FAIL = 'DELETE_SHIPMENT_ADMIN_FAIL';

export const DELETE_MEMBER_ADMIN = 'DELETE_MEMBER_ADMIN';
export const DELETE_MEMBER_ADMIN_SUCCESS = 'DELETE_MEMBER_ADMIN_SUCCESS';
export const DELETE_MEMBER_ADMIN_FAIL = 'DELETE_MEMBER_ADMIN_FAIL';

export const DELETE_INVOICE_ADMIN = 'DELETE_INVOICE_ADMIN';
export const DELETE_INVOICE_ADMIN_SUCCESS = 'DELETE_INVOICE_ADMIN_SUCCESS';
export const DELETE_INVOICE_ADMIN_FAIL = 'DELETE_INVOICE_ADMIN_FAIL';

export const GET_TERMS_ADMIN = 'GET_TERMS_ADMIN';
export const GET_TERMS_ADMIN_SUCCESS = 'GET_TERMS_ADMIN_SUCCESS';
export const GET_TERMS_ADMIN_FAIL = 'GET_TERMS_ADMIN_FAIL';

export const GET_FAQ_ADMIN = 'GET_FAQ_ADMIN';
export const GET_FAQ_ADMIN_SUCCESS = 'GET_FAQ_ADMIN_SUCCESS';
export const GET_FAQ_ADMIN_FAIL = 'GET_FAQ_ADMIN_FAIL';

export const ADD_FAQ_ADMIN = 'ADD_FAQ_ADMIN';
export const ADD_FAQ_ADMIN_SUCCESS = 'ADD_FAQ_ADMIN_SUCCESS';
export const ADD_FAQ_ADMIN_FAIL = 'ADD_FAQ_ADMIN_FAIL';

export const ADD_TERMS_ADMIN = 'ADD_TERMS_ADMIN';
export const ADD_TERMS_ADMIN_SUCCESS = 'ADD_TERMS_ADMIN_SUCCESS';
export const ADD_TERMS_ADMIN_FAIL = 'ADD_TERMS_ADMIN_FAIL';

export const PATCH_TERMS_ADMIN = 'PATCH_TERMS_ADMIN';
export const PATCH_TERMS_ADMIN_SUCCESS = 'PATCH_TERMS_ADMIN_SUCCESS';
export const PATCH_TERMS_ADMIN_FAIL = 'PATCH_TERMS_ADMIN_FAIL';

export const PATCH_FAQ_ADMIN = 'PATCH_FAQ_ADMIN';
export const PATCH_FAQ_ADMIN_SUCCESS = 'PATCH_FAQ_ADMIN_SUCCESS';
export const PATCH_FAQ_ADMIN_FAIL = 'PATCH_FAQ_ADMIN_FAIL';

export const GET_ORIGIN_PHOTO = 'GET_ORIGIN_PHOTO';
export const GET_ORIGIN_PHOTO_SUCCESS = 'GET_ORIGIN_PHOTO_SUCCESS';
export const GET_ORIGIN_PHOTO_FAIL = 'GET_ORIGIN_PHOTO_FAIL';

export const GET_ORIGIN_PHOTO_WITH_PAGINATION = 'GET_ORIGIN_PHOTO_WITH_PAGINATION';
export const GET_ORIGIN_PHOTO_WITH_PAGINATION_SUCCESS = 'GET_ORIGIN_PHOTO_WITH_PAGINATION_SUCCESS';
export const GET_ORIGIN_PHOTO_WITH_PAGINATION_FAIL = 'GET_ORIGIN_PHOTO_WITH_PAGINATION_FAIL';

// INDEXING
export const INDEX_ORIGIN_PHOTO = 'INDEX_ORIGIN_PHOTO';
export const INDEX_ORIGIN_PHOTO_SUCCESS = 'INDEX_ORIGIN_PHOTO_SUCCESS';
export const INDEX_ORIGIN_PHOTO_FAIL = 'INDEX_ORIGIN_PHOTO_FAIL';

export const INDEX_CHOICE_PHOTO = 'INDEX_CHOICE_PHOTO';
export const INDEX_CHOICE_PHOTO_SUCCESS = 'INDEX_CHOICE_PHOTO_SUCCESS';
export const INDEX_CHOICE_PHOTO_FAIL = 'INDEX_CHOICE_PHOTO_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const IS_TOKEN_EXISTS = 'IS_TOKEN_EXISTS';
export const IS_TOKEN_EXISTS_SUCCESS = 'IS_TOKEN_EXISTS_SUCCESS';
export const IS_TOKEN_EXISTS_FAIL = 'IS_TOKEN_EXISTS_FAIL';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const GET_ORIGIN_PHOTO_METADATA = 'GET_ORIGIN_PHOTO_METADATA';
export const GET_ORIGIN_PHOTO_METADATA_SUCCESS = 'GET_ORIGIN_PHOTO_METADATA_SUCCESS';
export const GET_ORIGIN_PHOTO_METADATA_FAIL = 'GET_ORIGIN_PHOTO_METADATA_FAIL';

export const UPDATE_SUBPACKAGE_IDX = 'UPDATE_SUBPACKAGE_IDX';

export const GET_SUBPACKAGE = 'GET_SUBPACKAGE';
export const GET_SUBPACKAGE_SUCCESS = 'GET_SUBPACKAGE_SUCCESS';
export const GET_SUBPACKAGE_FAIL = 'GET_SUBPACKAGE_FAIL';

export const RESET_ORIGIN_PHOTO = 'RESET_ORIGIN_PHOTO';

export const ORIGIN_SELECTED_PHOTO = 'ORIGIN_SELECTED_PHOTO';
export const ORIGIN_SELECTED_PHOTO_SUCCESS = 'ORIGIN_SELECTED_PHOTO_SUCCESS';
export const ORIGIN_SELECTED_PHOTO_FAIL = 'ORIGIN_SELECTED_PHOTO_FAIL';

export const ORIGIN_DELETE_PHOTO = 'ORIGIN_DELETE_PHOTO'
export const ORIGIN_DELETE_PHOTO_SUCCESS = 'ORIGIN_DELETE_PHOTO_SUCCESS';
export const ORIGIN_DELETE_PHOTO_FAIL = 'ORIGIN_DELETE_PHOTO_FAIL';

export const UPDATE_PAGE_NUMBER = 'UPDATE_PAGE_NUMBER';

export const UPDATE_SELECTED_ORIGIN_PHOTO = 'UPDATE_SELECTED_ORIGIN_PHOTO';

export const GET_COUNT_SELECTED_PHOTO = 'GET_COUNT_SELECTED_PHOTO';
export const GET_COUNT_SELECTED_PHOTO_SUCCESS   = 'GET_COUNT_SELECTED_PHOTO_SUCCESS';
export const GET_COUNT_SELECTED_PHOTO_FAIL = 'GET_COUNT_SELECTED_PHOTO_FAIL';

export const OPEN_ORIGIN_PHOTO_PREVIEW = 'OPEN_ORIGIN_PHOTO_PREVIEW';
export const UPDATE_CURRENT_PREVIEW_PHOTO = 'UPDATE_CURRENT_PREVIEW_PHOTO';

export const OPEN_ALERT_ORIGIN_PHOTO = 'OPEN_POPUP_ALERT_ORIGIN_PHOTO';

export const CHECKOUT_SELECTED_PHOTO = 'CHECKOUT_SELECTED_PHOTO';
export const CHECKOUT_SELECTED_PHOTO_SUCCESS = 'CHECKOUT_SELECTED_PHOTO_SUCCESS';
export const CHECKOUT_SELECTED_PHOTO_FAIL = 'CHECKOUT_SELECTED_PHOTO_FAIL';

export const GET_DOWNLOAD_LINK = 'GET_DONWLOAD_LINK';
export const GET_DOWNLOAD_LINK_SUCESS = 'GET_DONWLOAD_LINK_SUCCESS';
export const GET_DOWNLOAD_LINK_FAIL = 'GET_DONWLOAD_LINK_FAIL';

export const SET_OPEN_DOWNLOAD_POPUP = 'SET_OPEN_DOWNLOAD_POPUP';

export const SET_YESNO_DIALOG = 'SET_YESNO_DIALOG';


// CHOICE PHOTO ACTION
export const GET_CHOICE_PHOTO_METADATA = 'GET_CHOICE_PHOTO_METADATA';
export const GET_CHOICE_PHOTO_METADATA_SUCCESS = 'GET_CHOICE_PHOTO_METADATA_SUCCESS';
export const GET_CHOICE_PHOTO_METADATA_FAIL = 'GET_CHOICE_PHOTO_METADATA_FAIL';

export const GET_CHOICE_PHOTO_WITH_PAGINATION = 'GET_CHOICE_PHOTO_WITH_PAGINATION';
export const GET_CHOICE_PHOTO_WITH_PAGINATION_SUCCESS = 'GET_CHOICE_PHOTO_WITH_PAGINATION_SUCCESS';
export const GET_CHOICE_PHOTO_WITH_PAGINATION_FAIL = 'GET_CHOICE_PHOTO_WITH_PAGINATION_FAIL';

export const RESET_CHOICE_PHOTO = 'RESET_CHOICE_PHOTO';
export const OPEN_CHOICE_PHOTO_PREVIEW = 'OPEN_CHOICE_PHOTO_PREVIEW';

export const SELECT_ALBUM_PHOTO = 'SELECT_ALBUM_PHOTO';
export const SELECT_ALBUM_PHOTO_SUCCESS = 'SELECT_ALBUM_PHOTO_SUCCESS';
export const SELECT_ALBUM_PHOTO_FAIL = 'SELECT_ALBUM_PHOTO_FAIL';

export const SELECT_PRINT_PHOTO = 'SELECT_PRINT_PHOTO';
export const SELECT_PRINT_PHOTO_SUCCESS = 'SELECT_PRINT_PHOTO_SUCCESS';
export const SELECT_PRINT_PHOTO_FAIL = 'SELECT_PRINT_PHOTO_FAIL';

export const DELETE_ALBUM_PHOTO = 'DELETE_ALBUM_PHOTO';
export const DELETE_ALBUM_PHOTO_SUCCESS = 'DELETE_ALBUM_PHOTO_SUCCESS';
export const DELETE_ALBUM_PHOTO_FAIL = 'DELETE_ALBUM_PHOTO_FAIL';

export const DELETE_PRINT_PHOTO = 'DELETE_PRINT_PHOTO';
export const DELETE_PRINT_PHOTO_SUCCESS = 'DELETE_PRINT_PHOTO_SUCCESS';
export const DELETE_PRINT_PHOTO_FAIL = 'DELETE_PRINT_PHOTO_FAIL';

export const UPDATE_TOTAL_SELECTED_ALBUM = 'UPDATE_TOTAL_SELECTED_ALBUM';
export const UPDATE_TOTAL_SELECTED_ALBUM_SUCCESS = 'UPDATE_TOTAL_SELECTED_ALBUM_SUCCESS';
export const UPDATE_TOTAL_SELECTED_ALBUM_FAIL = 'UPDATE_TOTAL_SELECTED_ALBUM_FAIL';

export const UPDATE_TOTAL_SELECTED_PRINT = 'UPDATE_TOTAL_SELECTED_PRINT';
export const UPDATE_TOTAL_SELECTED_PRINT_SUCCESS = 'UPDATE_TOTAL_SELECTED_PRINT_SUCCESS';
export const UPDATE_TOTAL_SELECTED_PRINT_FAIL = 'UPDATE_TOTAL_SELECTED_PRINT_FAIL';

export const CHECKOUT_ALBUM_PRINT_PHOTO = 'CHECKOUT_ALBUM_PRINT_PHOTO'
export const CHECKOUT_ALBUM_PRINT_PHOTO_SUCCESS = 'CHECKOUT_ALBUM_PRINT_PHOTO_SUCCESS'
export const CHECKOUT_ALBUM_PRINT_PHOTO_FAIL = 'CHECKOUT_ALBUM_PRINT_PHOTO_FAIL'


// loading
export const SET_OPEN_LOADING = 'SET_OPEN_LOADING'

// alert
export const OPEN_ALERT = 'OPEN_ALERT';

//NOTIFICATION
export const GET_NOTIFICATION_USER = 'GET_NOTIFICATION_USER'
export const GET_NOTIFICATION_USER_SUCCESS = 'GET_NOTIFICATION_USER_SUCCESS'
export const GET_NOTIFICATION_USER_FAIL = 'GET_NOTIFICATION_USER_FAIL'

export const GET_NOTIFICATION_ADMIN = 'GET_NOTIFICATION_ADMIN'
export const GET_NOTIFICATION_ADMIN_SUCCESS = 'GET_NOTIFICATION_ADMIN_SUCCESS'
export const GET_NOTIFICATION_ADMIN_FAIL = 'GET_NOTIFICATION_ADMIN_FAIL'

export const UPDATE_IS_READ = 'UPDATE_IS_READ';
export const UPDATE_IS_READ_SUCCESS = 'UPDATE_IS_READ_SUCCESS';
export const UPDATE_IS_READ_FAIL = 'UPDATE_IS_READ_FAIL';

// albumphoto
export const GET_ALBUM_PHOTO = 'GET_ALBUM_PHOTO';
export const GET_ALBUM_PHOTO_SUCCESS = 'GET_ALBUM_PHOTO_SUCCESS';
export const GET_ALBUM_PHOTO_FAIL = 'GET_ALBUM_PHOTO_FAIL';
export const RESET_ALBUM_PHOTO = 'RESET_ALBUM_PHOTO';
export const SHOW_PREVIEW_ALBUM_PHOTO = 'SHOW_PREVIEW_ALBUM_PHOTO';